stages:
  - format
  - lint
  - test
  - deploy

format:
  stage: format
  image: ubuntu:22.04
  script:
    - apt-get update && apt-get install -y clang clang-format cmake git libwxgtk3.0-gtk3-dev
    - mkdir -p build
    - cd build
    - cmake ..
    - cmake --build . --target format
  allow_failure: false
  artifacts:
    paths:
      - build/  # Save build directory to use in later stages
  rules:
    - if: $CI_PIPELINE_SOURCE == 'merge_request_event' || ($CI_PIPELINE_SOURCE == "push" && $CI_COMMIT_REF_NAME == 'main')

lint:
  stage: lint
  image: ubuntu:22.04
  dependencies: 
    - format  # Reuse artifacts from the "format" stage
  script:
    - apt-get update && apt-get install -y clang clang-tidy cmake cppcheck libwxgtk3.0-gtk3-dev
    - cd build  # Use the existing build directory
    - cmake --build . --target check
  allow_failure: false
  rules:
    - if: $CI_PIPELINE_SOURCE == 'merge_request_event' || ($CI_PIPELINE_SOURCE == "push" && $CI_COMMIT_REF_NAME == 'main')

test:
  stage: test
  image: ubuntu:22.04
  dependencies: 
    - lint  # Reuse artifacts from the "lint" stage
  script:
    - apt-get update && apt-get install -y clang cmake libwxgtk3.0-gtk3-dev
    - cd build  # Use the existing build directory
    - cmake --build . -j $(nproc)
    - ctest --output-on-failure
  allow_failure: false
  rules:
    - if: $CI_PIPELINE_SOURCE == 'merge_request_event' || ($CI_PIPELINE_SOURCE == "push" && $CI_COMMIT_REF_NAME == 'main')

deploy:
  stage: deploy
  image: ubuntu:22.04
  dependencies:
    - test  # Ensure successful test completion before deploying
  script:
    - apt-get update && apt-get install -y openssh-client
    - mkdir -p ~/.ssh
    - base64 -d $SSH_DEPLOY_KEY > ~/.ssh/id_rsa
    - chmod 600 ~/.ssh/id_rsa
    - ssh-keyscan -H se.nicolabruhin.com >> ~/.ssh/known_hosts
    - ssh dominion@se.nicolabruhin.com "cd /opt/dominion/dominion && git pull && cd docker && docker compose up -d --build"
  environment:
    name: production
  rules:
    - if: $CI_PIPELINE_SOURCE == 'push' && $CI_COMMIT_REF_NAME == 'main'
      when: on_success
    - when: never
